### ISSUE TITLE
 disable specific node-widget classes, including comments. (Do it for unreal 5 please)

### ISSUE THREAD

**Issue by rkgdgames** [AgitoReiKen/ue-restyle#12]
I did an option to disable specific node-widget classes, including comments. However it's a feature for v5.1 only 

(If you need it for v5.0, please create issue on github, i'll update it asap)

Go to Restyle[Default][Node], scroll down until you see "Override" section, there will be "Disabled Widgets" property,

Turn on Kismet -> Comment, and Other -> Comment

**Comment by AgitoReiKen** [comment]
https://github.com/AgitoReiKen/ue-restyle/commit/0a0510f2fb3961e701ca0916b9bb740a259575cf
